# Generated by Django 2.0.13 on 2019-05-07 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Done', 'Done')], max_length=255, null=True)),
                ('Due_Date', models.DateField(default=django.utils.timezone.now)),
                ('Text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
