# Generated by Django 2.0.13 on 2019-05-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190508_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
